# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

parameters:
- name: string # Required as first property.
  displayName: string # Human-readable name for the parameter.
  type: string
  default: string
  values: [ string, string2 ]

variables:
- group: kvgroup

pool: training-pool

jobs:
- job: job1 # Required as first property. ID of the job.
  displayName: string # Human-readable name for the job.
  steps:
  - script: echo Hello, world!
    displayName: 'Run a one-line $(test1)'

  - script: |
      echo Add other tasks to build, test, and deploy your project.
      echo See https://aka.ms/yaml
    displayName: 'Run a multi-line script'

- job: job2 # Required as first property. ID of the job.
  displayName: string # Human-readable name for the job.
  steps:
  - script: echo Hello, world!
    displayName: 'Run a one-line ${{ parameters.string }}'

  - script: |
      echo Add other tasks to build, test, and deploy your project.
      echo See https://aka.ms/yaml
    displayName: 'Run a multi-line script'

  - task: Bash@3
    inputs:
      targetType: 'inline'
      script: |
        # Write your commands here
        
        echo 'Hello world'